name: st_manager
description: ST_Manager - MikroTik Network Management
publish_to: 'none'
version: 2.4.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  url_launcher: ^6.3.0
  pdf: ^3.11.0
  printing: ^5.13.1
  share_plus: ^12.0.2               # <-- تم التحديث لحل التعارض
  fl_chart: ^0.69.0
  path_provider: ^2.1.4            # <-- الاسم الصحيح
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  syncfusion_flutter_gauges: ^27.1.48
  uuid: ^4.5.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/